### PR TITLE
Npm

### PR DESCRIPTION
**Pull request by trusktr**

### CODE REVIEW

**Comment by trusktr** [comment]
@guybedford I got a request from someone to update the version of system-css on npmjs. Don't know why I didn't think of this before, I made you owner of the following npm packages:

- [system-css](https://www.npmjs.com/package/system-css)
- [system-font](https://www.npmjs.com/package/system-font)
- [system-image](https://www.npmjs.com/package/system-image)
- [system-jsx](https://www.npmjs.com/package/system-jsx)
- [system-md](https://www.npmjs.com/package/system-md)
- [system-text](https://www.npmjs.com/package/system-text)

**Comment by trusktr** [comment]
@dchambers, I added you to system-css on npmjs.com too if you'd like to update it. It's based on my npm branch (difference seen in this PR): https://github.com/trusktr/system-css/tree/npm

**Comment by trusktr** [comment]
@dchambers, How's your workflow? Are you using SystemJS directly, getting system-css with npm? Or doing it all via JSPM? @guybedford might be curious to know.

**Comment by dchambers** [comment]
Hi @trusktr,

Sorry for the slow response, I've been on holiday with no Internet connection most of the time.

> @dchambers, I added you to system-css on npmjs.com too if you'd like to update it.

Thanks so much! I'll take a look at updating to a newer version tonight.

> @dchambers, How's your workflow? Are you using SystemJS directly, getting system-css with npm? Or doing it all via JSPM? @guybedford might be curious to know.

I have a number of workflows, including using SystemJS both via NPM and JSPM. I'm actually planning to publish a blog article describing these at some point, and will link it from this issue once that's done.

I also tried linking directly to the Github project from my `package.json`, but [that doesn't seem to work at present](https://github.com/systemjs/plugin-css/issues/1#issuecomment-117999181).

**Comment by dchambers** [comment]
Hi @trusktr,

For reasons I don't understand I've so far been unable to test changes to `system-css` locally using another project on my machine. I've tried both using `file:` and `npm install` with a local file path. As a last option, I also tried publishing to NPM, but this just seemed to publish what was on GitHub, rather than what is on my local machine.

I've since unpublished the new versions I created, so that anyone else using this NPM package gets the last known working version. My fork of your fork is available [here](https://github.com/dchambers/system-css/tree/npm).

Any ideas about how I can test locally without publishing to NPM, or why NPM isn't publishing the files I have on my machine?

**Comment by dchambers** [comment]
Okay, ignore me. `file:` only didn't work because my `config.js` was still expecting there to be a `node_module/system-css` directory. I've since switched to using a symbolic link for the `node_module/system-css` directory, and I'm able to make progress again...

**Comment by trusktr** [comment]
Awesome, glad you got it working. Have you tried [`npm link`](https://docs.npmjs.com/cli/link) for managing symlinks?

**Comment by pe8ter** [comment]
@guybedford [made](https://github.com/systemjs/plugin-css/issues/66) an [official npm package](https://www.npmjs.com/package/systemjs-plugin-css). I don't think this PR is needed anymore.

**Comment by dchambers** [comment]
Excellent news :simple-smile:

**Pull request closed without merging**
