### PR TITLE
Update css-builder.js

### PR DESCRIPTION
**Pull request by robcleghorn**
Fix change to support both mac and windows paths eg file://xyz and file:c:/xyz and file://c:/xyz

### CODE REVIEW

**Comment by Klaster1** [comment]
That was fast, any info on how soon the pull request will be merged?

**Comment by guybedford** [comment]
Thanks so much for contributing!

**Comment by jannisg** [comment]
@guybedford Is there any chance we can see this fix being pushed out as a hotfix of some kind that we can use with our JSPM (0.15.7) bundle task in the next couple of days? All our automated processes are running on Windows servers and are currently unable to build due to this bug.

**Comment by guybedford** [comment]
@jannisg sure I've pushed out a new release.

**Comment by sinasalek** [comment]
Was using 0.1.27 and the problem still exists.
Tried previous versions and the last one that works is 0.1.25
I'm on Windows BTW

**Comment by guybedford** [comment]
@sinasalek can you create a new issue for this and share a replication? The only change from 0.1.25 -> 0.1.26 is https://github.com/systemjs/plugin-css/commit/ff1886842e1e1d820d3a6747584b8945e21795c8.

**Comment by sinasalek** [comment]
There is already a new issue for 0.1.27 #108

**Pull request merged**
